export { CatalogByCategory } from "./CatalogByCategory";
export { default as CatalogBySearch } from "./CatalogBySearch";
export { default as Contacts } from "./Contacts";
export { default as Main } from "./Main";
export { default as NotFound } from "./NotFound";
export { default as FAQ } from "./FAQ";
export { default as Settings } from "./Settings";
export { default as ShoppingCart } from "./ShoppingCart";
export { default as Product } from "./Product";
export { default as AboutUs } from "./AboutUs";
